baseURL = "https://rizin.netlify.app/"
languageCode = "en-us"
title = "Rizin | Package Manager"
theme = "ananke"
toc = true

ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    identifier = "packages"
    name = "Packages"
    url = "/packages/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 40

